using System.Xml.Serialization;

namespace Mozu.AubuchonDataAdapter.Domain.Contracts
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.34209
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.18020.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(ElementName = "message", Namespace = "", IsNullable = false)]
    public class CatalogMessage
    {

        private object[] _itemsField;

        /// <remarks/>
        [XmlElementAttribute("body", typeof(CatalogMessageBody), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElementAttribute("head", typeof(MessageHead), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElementAttribute("prerequisites", typeof(Prerequisites))]
        public object[] Items
        {
            get
            {
                return _itemsField;
            }
            set
            {
                _itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class CatalogMessageBody
    {

        private MessageBodyCatalogimport[] _catalogimportField;

        /// <remarks/>
        [XmlElementAttribute("Catalogimport", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyCatalogimport[] Catalogimport
        {
            get
            {
                return _catalogimportField;
            }
            set
            {
                _catalogimportField = value;
            }
        }
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRootAttribute(Namespace = "", IsNullable = false)]
    
    public class Prerequisites
    {

        private Prerequisites[] _prerequisites1Field;

        /// <remarks/>
        [XmlElementAttribute("prerequisites")]
        public Prerequisites[] Prerequisites1
        {
            get
            {
                return _prerequisites1Field;
            }
            set
            {
                _prerequisites1Field = value;
            }
        }
    }

   

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyCatalogimport
    {

        private string _statuscodeField;

        private string _itemtypenameField;

        private string _uomnameField;

        private string _catalogitemField;

        private string _catalognameField;

        private string _catalognotesField;

        private string _retailpriceField;

        private string _shortdescriptionField;

        private string _longdescriptionField;

        private string _orderquantityField;

        private string _custodianusernameField;

        private string _defaultdeliverymethodcodeField;

        private string _minorderqtyField;

        private string _maxorderqtyField;

        private string _shippingamountField;

        private string _handlingamountField;

        private string _salesaccountField;

        private string _sortorderField;

        private string _iselectronicField;

        private string _downloadableField;

        private string _taxableField;

        private string _allowautoshipField;

        private string _chargeshippingField;

        private string _taxresellersField;

        private string _startdateField;

        private string _enddateField;

        private string _catalogcodeField;

        private string _budgetitemField;

        private string _searchableField;

        private string _dutytaxField;

        private MessageBodyCatalogimportSkus[] _skusField;

        private MessageBodyCatalogimportFilenamesFilename[] _filenamesField;

        private MessageBodyCatalogimportProjectsProject[] _projectsField;

        private MessageBodyCatalogimportCategoriesCategoryCode[] _categoriesField;

        private Prerequisites[] _prerequisitesField;

        private MessageBodyCatalogimportDeliverymethodcodes[] _deliverymethodcodesField;

        private MessageBodyCatalogimportPriceListsPriceList[] _priceListsField;

        private MessageBodyCatalogimportDynamicfieldsDynamicfield[] _dynamicfieldsField;
        private string _catalogTaxClassCode;

        /// <remarks/>
        [XmlElementAttribute(ElementName = "statuscode",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Statuscode
        {
            get
            {
                return _statuscodeField;
            }
            set
            {
                _statuscodeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "itemtypename",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Itemtypename
        {
            get
            {
                return _itemtypenameField;
            }
            set
            {
                _itemtypenameField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "uomname",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Uomname
        {
            get
            {
                return _uomnameField;
            }
            set
            {
                _uomnameField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "catalogitem",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Catalogitem
        {
            get
            {
                return _catalogitemField;
            }
            set
            {
                _catalogitemField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "catalogname",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Catalogname
        {
            get
            {
                return _catalognameField;
            }
            set
            {
                _catalognameField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "catalognotes",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Catalognotes
        {
            get
            {
                return _catalognotesField;
            }
            set
            {
                _catalognotesField = value;
            }
        }


        [XmlElementAttribute(ElementName = "catalogTaxClassCode", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CatalogTaxClassCode
        {
            get { return _catalogTaxClassCode; }
            set { _catalogTaxClassCode = value; }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "retailprice",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Retailprice
        {
            get
            {
                return _retailpriceField;
            }
            set
            {
                _retailpriceField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "shortdescription",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Shortdescription
        {
            get
            {
                return _shortdescriptionField;
            }
            set
            {
                _shortdescriptionField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "longdescription",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Longdescription
        {
            get
            {
                return _longdescriptionField;
            }
            set
            {
                _longdescriptionField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "orderquantity",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Orderquantity
        {
            get
            {
                return _orderquantityField;
            }
            set
            {
                _orderquantityField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "custodianusername",Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Custodianusername
        {
            get
            {
                return _custodianusernameField;
            }
            set
            {
                _custodianusernameField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "defaultdeliverymethodcode", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Defaultdeliverymethodcode
        {
            get
            {
                return _defaultdeliverymethodcodeField;
            }
            set
            {
                _defaultdeliverymethodcodeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "minorderqty", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Minorderqty
        {
            get
            {
                return _minorderqtyField;
            }
            set
            {
                _minorderqtyField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "maxorderqty", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Maxorderqty
        {
            get
            {
                return _maxorderqtyField;
            }
            set
            {
                _maxorderqtyField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "shippingamount", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Shippingamount
        {
            get
            {
                return _shippingamountField;
            }
            set
            {
                _shippingamountField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "handlingamount", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Handlingamount
        {
            get
            {
                return _handlingamountField;
            }
            set
            {
                _handlingamountField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "salesaccount", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Salesaccount
        {
            get
            {
                return _salesaccountField;
            }
            set
            {
                _salesaccountField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "sortorder", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sortorder
        {
            get
            {
                return _sortorderField;
            }
            set
            {
                _sortorderField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "iselectronic", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Iselectronic
        {
            get
            {
                return _iselectronicField;
            }
            set
            {
                _iselectronicField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "downloadable", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Downloadable
        {
            get
            {
                return _downloadableField;
            }
            set
            {
                _downloadableField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "taxable", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Taxable
        {
            get
            {
                return _taxableField;
            }
            set
            {
                _taxableField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "allowautoship", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Allowautoship
        {
            get
            {
                return _allowautoshipField;
            }
            set
            {
                _allowautoshipField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "chargeshipping", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Chargeshipping
        {
            get
            {
                return _chargeshippingField;
            }
            set
            {
                _chargeshippingField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "taxresellers", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Taxresellers
        {
            get
            {
                return _taxresellersField;
            }
            set
            {
                _taxresellersField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "startdate", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Startdate
        {
            get
            {
                return _startdateField;
            }
            set
            {
                _startdateField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "enddate", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Enddate
        {
            get
            {
                return _enddateField;
            }
            set
            {
                _enddateField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "catalogcode", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Catalogcode
        {
            get
            {
                return _catalogcodeField;
            }
            set
            {
                _catalogcodeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "budgetitem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Budgetitem
        {
            get
            {
                return _budgetitemField;
            }
            set
            {
                _budgetitemField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "searchable", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Searchable
        {
            get
            {
                return _searchableField;
            }
            set
            {
                _searchableField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(ElementName = "dutytax", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dutytax
        {
            get
            {
                return _dutytaxField;
            }
            set
            {
                _dutytaxField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("skus", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyCatalogimportSkus[] Skus
        {
            get
            {
                return _skusField;
            }
            set
            {
                _skusField = value;
            }
        }

        /// <remarks/>
        [XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("filename", typeof(MessageBodyCatalogimportFilenamesFilename), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyCatalogimportFilenamesFilename[] Filenames
        {
            get
            {
                return _filenamesField;
            }
            set
            {
                _filenamesField = value;
            }
        }

        /// <remarks/>
        [XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("project", typeof(MessageBodyCatalogimportProjectsProject), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyCatalogimportProjectsProject[] Projects
        {
            get
            {
                return _projectsField;
            }
            set
            {
                _projectsField = value;
            }
        }

        /// <remarks/>
        [XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("categoryCode", typeof(MessageBodyCatalogimportCategoriesCategoryCode), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyCatalogimportCategoriesCategoryCode[] Categories
        {
            get
            {
                return _categoriesField;
            }
            set
            {
                _categoriesField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("prerequisites")]
        public Prerequisites[] Prerequisites
        {
            get
            {
                return _prerequisitesField;
            }
            set
            {
                _prerequisitesField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("deliverymethodcodes", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyCatalogimportDeliverymethodcodes[] Deliverymethodcodes
        {
            get
            {
                return _deliverymethodcodesField;
            }
            set
            {
                _deliverymethodcodesField = value;
            }
        }

        /// <remarks/>
        [XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("PriceList", typeof(MessageBodyCatalogimportPriceListsPriceList), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public MessageBodyCatalogimportPriceListsPriceList[] PriceLists
        {
            get
            {
                return _priceListsField;
            }
            set
            {
                _priceListsField = value;
            }
        }

        /// <remarks/>
        [XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("DYNAMICFIELD", typeof(MessageBodyCatalogimportDynamicfieldsDynamicfield), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public MessageBodyCatalogimportDynamicfieldsDynamicfield[] Dynamicfields
        {
            get
            {
                return _dynamicfieldsField;
            }
            set
            {
                _dynamicfieldsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyCatalogimportSkus
    {

        private string _skuField;

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sku
        {
            get
            {
                return _skuField;
            }
            set
            {
                _skuField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyCatalogimportFilenamesFilename
    {

        private string _valueField;
        private string _default;

        [XmlAttribute("default")]
        public string Default
        {
            get { return _default; }
            set { _default = value; }
        }

        /// <remarks/>
        [XmlTextAttribute]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyCatalogimportProjectsProject
    {

        private string _valueField;

        /// <remarks/>
        [XmlTextAttribute]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyCatalogimportCategoriesCategoryCode
    {

        private string _valueField;

        /// <remarks/>
        [XmlTextAttribute]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyCatalogimportDeliverymethodcodes
    {

        private string _deliverymethodcodeField;

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Deliverymethodcode
        {
            get
            {
                return _deliverymethodcodeField;
            }
            set
            {
                _deliverymethodcodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyCatalogimportPriceListsPriceList
    {

        private string _startRangeField;

        private string _endRangeField;

        private string _changeValueField;

        private string _priceChangeCodeField;

        private string _priceListCodeField;

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StartRange
        {
            get
            {
                return _startRangeField;
            }
            set
            {
                _startRangeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EndRange
        {
            get
            {
                return _endRangeField;
            }
            set
            {
                _endRangeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ChangeValue
        {
            get
            {
                return _changeValueField;
            }
            set
            {
                _changeValueField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PriceChangeCode
        {
            get
            {
                return _priceChangeCodeField;
            }
            set
            {
                _priceChangeCodeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PriceListCode
        {
            get
            {
                return _priceListCodeField;
            }
            set
            {
                _priceListCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyCatalogimportDynamicfieldsDynamicfield
    {

        private string _dYnamicfieldcodeField;

        private string _dYnamicfieldvalueField;
        private string _dynamicFieldLabel;

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dynamicfieldcode
        {
            get
            {
                return _dYnamicfieldcodeField;
            }
            set
            {
                _dYnamicfieldcodeField = value;
            }
        }

        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DynamicFieldLabel
        {
            get { return _dynamicFieldLabel; }
            set { _dynamicFieldLabel = value; }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dynamicfieldvalue
        {
            get
            {
                return _dYnamicfieldvalueField;
            }
            set
            {
                _dYnamicfieldvalueField = value;
            }
        }
    }

    


}
