using System.Xml.Serialization;

namespace Mozu.AubuchonDataAdapter.Domain.Contracts
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.34209
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.18020.
    // 

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    [XmlRoot(ElementName = "message", Namespace = "", IsNullable = false)]
    public class InventoryMessage
    {

        private object[] _itemsField;

        /// <remarks/>
        [XmlElementAttribute("body", typeof(InventoryMessageBody), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlElementAttribute("head", typeof(MessageHead), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items
        {
            get
            {
                return _itemsField;
            }
            set
            {
                _itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class InventoryMessageBody
    {

        private MessageBodyInventoryimport[] _inventoryimportField;

        /// <remarks/>
        [XmlElementAttribute("Inventoryimport", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyInventoryimport[] Inventoryimport
        {
            get
            {
                return _inventoryimportField;
            }
            set
            {
                _inventoryimportField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyInventoryimport
    {

        private string _skuField;

        private string _descriptionField;

        private string _skutypecodeField;

        private string _manufacturernameField;

        private string _uomnameField;

        private string _manufacturerpartnoField;

        private string _costField;

        private string _reorderpointField;

        private string _maxbuildqtyField;

        private string _qtyperpackageField;

        private string _leadtimeField;

        private string _allowbackorderField;

        private string _statuscodeField;

        private string _statusdateField;

        private string _custodianusernameField;

        private string _parentskuField;

        private string _inventoryField;

        private string _returnableField;

        private string _refundableField;

        private string _restockableField;

        private string _obsoleteField;

        private string _weightField;

        private string _lengthField;

        private string _widthField;

        private string _heightField;

        private string _lwhunitField;

        private string _upcnumberField;

        private string _trademarknameField;

        private string _legacynumberField;

        private string _hazardclassField;

        private string _packaginggroupField;

        private string _colornameField;

        private string _sizenameField;

        private string _stylenameField;

        private string _inventorynotesField;

        private string _skuplacementcodeField;

        private string _forecasteddateField;

        private string _reorderrulecodeField;

        private string _reorderqtyField;

        private string _avgdailyusageField;

        private string _secureshipmentField;

        private string _graceperiodField;

        private string _docktostockField;

        private string _minbuildqtyField;

        private string _startdateField;

        private string _enddateField;

        private MessageBodyInventoryimportFilenamesFilename[] _filenamesField;

        private MessageBodyInventoryimportCategoriesCategoryCode[] _categoriesField;

        private MessageBodyInventoryimportProviders _providersField;

        private MessageBodyInventoryimportSuppliers[] _suppliersField;

        private MessageBodyInventoryimportProjectsProject[] _projectsField;

        private MessageBodyInventoryimportLocalesLocale[] _localesField;

        private MessageBodyInventoryimportDynamicfieldsDynamicfield[] _dynamicfieldsField;
        private string _inventoryNotes;

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sku
        {
            get
            {
                return _skuField;
            }
            set
            {
                _skuField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description
        {
            get
            {
                return _descriptionField;
            }
            set
            {
                _descriptionField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Skutypecode
        {
            get
            {
                return _skutypecodeField;
            }
            set
            {
                _skutypecodeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Manufacturername
        {
            get
            {
                return _manufacturernameField;
            }
            set
            {
                _manufacturernameField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Uomname
        {
            get
            {
                return _uomnameField;
            }
            set
            {
                _uomnameField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Manufacturerpartno
        {
            get
            {
                return _manufacturerpartnoField;
            }
            set
            {
                _manufacturerpartnoField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cost
        {
            get
            {
                return _costField;
            }
            set
            {
                _costField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Reorderpoint
        {
            get
            {
                return _reorderpointField;
            }
            set
            {
                _reorderpointField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Maxbuildqty
        {
            get
            {
                return _maxbuildqtyField;
            }
            set
            {
                _maxbuildqtyField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Qtyperpackage
        {
            get
            {
                return _qtyperpackageField;
            }
            set
            {
                _qtyperpackageField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Leadtime
        {
            get
            {
                return _leadtimeField;
            }
            set
            {
                _leadtimeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Allowbackorder
        {
            get
            {
                return _allowbackorderField;
            }
            set
            {
                _allowbackorderField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Statuscode
        {
            get
            {
                return _statuscodeField;
            }
            set
            {
                _statuscodeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Statusdate
        {
            get
            {
                return _statusdateField;
            }
            set
            {
                _statusdateField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Custodianusername
        {
            get
            {
                return _custodianusernameField;
            }
            set
            {
                _custodianusernameField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Parentsku
        {
            get
            {
                return _parentskuField;
            }
            set
            {
                _parentskuField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Inventory
        {
            get
            {
                return _inventoryField;
            }
            set
            {
                _inventoryField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Returnable
        {
            get
            {
                return _returnableField;
            }
            set
            {
                _returnableField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Refundable
        {
            get
            {
                return _refundableField;
            }
            set
            {
                _refundableField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Restockable
        {
            get
            {
                return _restockableField;
            }
            set
            {
                _restockableField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Obsolete
        {
            get
            {
                return _obsoleteField;
            }
            set
            {
                _obsoleteField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Weight
        {
            get
            {
                return _weightField;
            }
            set
            {
                _weightField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Length
        {
            get
            {
                return _lengthField;
            }
            set
            {
                _lengthField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Width
        {
            get
            {
                return _widthField;
            }
            set
            {
                _widthField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Height
        {
            get
            {
                return _heightField;
            }
            set
            {
                _heightField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Lwhunit
        {
            get
            {
                return _lwhunitField;
            }
            set
            {
                _lwhunitField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Upcnumber
        {
            get
            {
                return _upcnumberField;
            }
            set
            {
                _upcnumberField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Trademarkname
        {
            get
            {
                return _trademarknameField;
            }
            set
            {
                _trademarknameField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Legacynumber
        {
            get
            {
                return _legacynumberField;
            }
            set
            {
                _legacynumberField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Hazardclass
        {
            get
            {
                return _hazardclassField;
            }
            set
            {
                _hazardclassField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Packaginggroup
        {
            get
            {
                return _packaginggroupField;
            }
            set
            {
                _packaginggroupField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Colorname
        {
            get
            {
                return _colornameField;
            }
            set
            {
                _colornameField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sizename
        {
            get
            {
                return _sizenameField;
            }
            set
            {
                _sizenameField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Stylename
        {
            get
            {
                return _stylenameField;
            }
            set
            {
                _stylenameField = value;
            }
        }

        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryNotes
        {
            get { return _inventoryNotes; }
            set { _inventoryNotes = value; }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Jnventorynotes
        {
            get
            {
                return _inventorynotesField;
            }
            set
            {
                _inventorynotesField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Skuplacementcode
        {
            get
            {
                return _skuplacementcodeField;
            }
            set
            {
                _skuplacementcodeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Forecasteddate
        {
            get
            {
                return _forecasteddateField;
            }
            set
            {
                _forecasteddateField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Reorderrulecode
        {
            get
            {
                return _reorderrulecodeField;
            }
            set
            {
                _reorderrulecodeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Reorderqty
        {
            get
            {
                return _reorderqtyField;
            }
            set
            {
                _reorderqtyField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Avgdailyusage
        {
            get
            {
                return _avgdailyusageField;
            }
            set
            {
                _avgdailyusageField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Secureshipment
        {
            get
            {
                return _secureshipmentField;
            }
            set
            {
                _secureshipmentField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Graceperiod
        {
            get
            {
                return _graceperiodField;
            }
            set
            {
                _graceperiodField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Docktostock
        {
            get
            {
                return _docktostockField;
            }
            set
            {
                _docktostockField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Minbuildqty
        {
            get
            {
                return _minbuildqtyField;
            }
            set
            {
                _minbuildqtyField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Startdate
        {
            get
            {
                return _startdateField;
            }
            set
            {
                _startdateField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Enddate
        {
            get
            {
                return _enddateField;
            }
            set
            {
                _enddateField = value;
            }
        }

        /// <remarks/>
        [XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("filename", typeof(MessageBodyInventoryimportFilenamesFilename), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyInventoryimportFilenamesFilename[] Filenames
        {
            get
            {
                return _filenamesField;
            }
            set
            {
                _filenamesField = value;
            }
        }

        /// <remarks/>
        [XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("categoryCode", typeof(MessageBodyInventoryimportCategoriesCategoryCode), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyInventoryimportCategoriesCategoryCode[] Categories
        {
            get
            {
                return _categoriesField;
            }
            set
            {
                _categoriesField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("providers", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyInventoryimportProviders Providers
        {
            get
            {
                return _providersField;
            }
            set
            {
                _providersField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute("suppliers", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyInventoryimportSuppliers[] Suppliers
        {
            get
            {
                return _suppliersField;
            }
            set
            {
                _suppliersField = value;
            }
        }

        /// <remarks/>
        [XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("project", typeof(MessageBodyInventoryimportProjectsProject), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyInventoryimportProjectsProject[] Projects
        {
            get
            {
                return _projectsField;
            }
            set
            {
                _projectsField = value;
            }
        }

        /// <remarks/>
        [XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("Locale", typeof(MessageBodyInventoryimportLocalesLocale), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public MessageBodyInventoryimportLocalesLocale[] Locales
        {
            get
            {
                return _localesField;
            }
            set
            {
                _localesField = value;
            }
        }

        /// <remarks/>
        [XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [XmlArrayItemAttribute("DYNAMICFIELD", typeof(MessageBodyInventoryimportDynamicfieldsDynamicfield), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public MessageBodyInventoryimportDynamicfieldsDynamicfield[] Dynamicfields
        {
            get
            {
                return _dynamicfieldsField;
            }
            set
            {
                _dynamicfieldsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyInventoryimportFilenamesFilename
    {

        private string _defaultField;

        private string _valueField;

        /// <remarks/>
        [XmlAttributeAttribute]
        public string Default
        {
            get
            {
                return _defaultField;
            }
            set
            {
                _defaultField = value;
            }
        }

        /// <remarks/>
        [XmlTextAttribute]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyInventoryimportCategoriesCategoryCode
    {

        private string _valueField;

        /// <remarks/>
        [XmlTextAttribute]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyInventoryimportProviders
    {

        private MessageBodyInventoryimportProvidersProviderCode[] _field;

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified,ElementName = "providercode")]
        public MessageBodyInventoryimportProvidersProviderCode[] ProviderCode
        {
            get
            {
                return _field;
            }
            set
            {
                _field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyInventoryimportProvidersProviderCode
    {

        private string _field;

        /// <remarks/>
         [XmlTextAttribute()]
        public string ProviderCode
        {
            get
            {
                return _field;
            }
            set
            {
                _field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyInventoryimportSuppliers
    {

        private string _supplierField;

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Supplier
        {
            get
            {
                return _supplierField;
            }
            set
            {
                _supplierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyInventoryimportProjectsProject
    {

        private string _valueField;

        /// <remarks/>
        [XmlTextAttribute]
        public string Value
        {
            get
            {
                return _valueField;
            }
            set
            {
                _valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyInventoryimportLocalesLocale
    {

        private string _localeCodeField;

        private string _descriptionField;

        private string _inventoryNotesField;

        private string _costField;

        private string _retailPriceField;

        private string _salePriceField;

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocaleCode
        {
            get
            {
                return _localeCodeField;
            }
            set
            {
                _localeCodeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description
        {
            get
            {
                return _descriptionField;
            }
            set
            {
                _descriptionField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryNotes
        {
            get
            {
                return _inventoryNotesField;
            }
            set
            {
                _inventoryNotesField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cost
        {
            get
            {
                return _costField;
            }
            set
            {
                _costField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RetailPrice
        {
            get
            {
                return _retailPriceField;
            }
            set
            {
                _retailPriceField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalePrice
        {
            get
            {
                return _salePriceField;
            }
            set
            {
                _salePriceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyInventoryimportDynamicfieldsDynamicfield
    {

        private string _dYnamicfieldcodeField;

        private string _dYnamicfieldvalueField;

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dynamicfieldcode
        {
            get
            {
                return _dYnamicfieldcodeField;
            }
            set
            {
                _dYnamicfieldcodeField = value;
            }
        }

        /// <remarks/>
        [XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Dynamicfieldvalue
        {
            get
            {
                return _dYnamicfieldvalueField;
            }
            set
            {
                _dYnamicfieldvalueField = value;
            }
        }
    }

   

}
