using System.Xml.Serialization;

namespace Mozu.AubuchonDataAdapter.Domain.Contracts
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.34209
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------
    
    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 
    

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public class DynamicField
    {

        private string _dynamicFieldCodeField;

        private string _dynamicFieldLabelField;

        private string _dynamicFieldValueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DynamicFieldCode
        {
            get
            {
                return _dynamicFieldCodeField;
            }
            set
            {
                _dynamicFieldCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DynamicFieldLabel
        {
            get
            {
                return _dynamicFieldLabelField;
            }
            set
            {
                _dynamicFieldLabelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DynamicFieldValue
        {
            get
            {
                return _dynamicFieldValueField;
            }
            set
            {
                _dynamicFieldValueField = value;
            }
        }
    }

    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "Message", IsNullable = false)]
    public class OrderMessage
    {

        private object[] _itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("body", typeof(OrderMessageBody), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("dynamicField", typeof(DynamicField))]
        [System.Xml.Serialization.XmlElementAttribute("head", typeof(MessageHead), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] Items
        {
            get
            {
                return _itemsField;
            }
            set
            {
                _itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class OrderMessageBody
    {

        private MessageBodyOrderImportOrderHeader[] _orderImportField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("orderHeader", typeof(MessageBodyOrderImportOrderHeader), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public MessageBodyOrderImportOrderHeader[] OrderImport
        {
            get
            {
                return _orderImportField;
            }
            set
            {
                _orderImportField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyOrderImportOrderHeader
    {

        private string _merchantCodeField;

        private string _projectCodeField;

        private string _ordertypeCodeField;

        private string _localeCodeField;

        private string _orderedByUserNameField;

        private string _custodianUserNameField;

        private string _clientreferenceField;

        private string _referencefield1Field;

        private string _referencefield2Field;

        private string _referencefield3Field;

        private string _referencefield4Field;

        private string _referencefield5Field;

        private string _distributionJobNumberField;

        private string _commentsField;

        private string _ordernotesField;

        private string _shipcompleteField;

        private string _orderStatusCodeField;

        private string _providerCodeField;

        private string _priorityCodeField;

        private string _workOrderTypeCodeField;

        private string _affiliateCodeField;

        private string _marketingSourceCodeField;

        private string _releaseDateField;

        private string _orderSourceCodeField;

        private string _workOrderReferenceField;

        private string _completeByDateField;

        private string _promotionCodeField;

        private string _salesTerritoryCodeField;

        private string _billingCodeField;

        private string _budgetCenterCodeField;

        private string _exceptionTypeField;

        private string _exceptionMessageField;

        private MessageBodyOrderImportOrderHeaderBillToAddress[] _billToAddressField;

        private MessageBodyOrderImportOrderHeaderPayments[] _paymentsField;

        private DynamicField[] _dynamicFieldField;

        private MessageBodyOrderImportOrderHeaderOrderDetail[] _orderDetailField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MerchantCode
        {
            get
            {
                return _merchantCodeField;
            }
            set
            {
                _merchantCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProjectCode
        {
            get
            {
                return _projectCodeField;
            }
            set
            {
                _projectCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrdertypeCode
        {
            get
            {
                return _ordertypeCodeField;
            }
            set
            {
                _ordertypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LocaleCode
        {
            get
            {
                return _localeCodeField;
            }
            set
            {
                _localeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderedByUserName
        {
            get
            {
                return _orderedByUserNameField;
            }
            set
            {
                _orderedByUserNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustodianUserName
        {
            get
            {
                return _custodianUserNameField;
            }
            set
            {
                _custodianUserNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Clientreference
        {
            get
            {
                return _clientreferenceField;
            }
            set
            {
                _clientreferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Referencefield1
        {
            get
            {
                return _referencefield1Field;
            }
            set
            {
                _referencefield1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Referencefield2
        {
            get
            {
                return _referencefield2Field;
            }
            set
            {
                _referencefield2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Referencefield3
        {
            get
            {
                return _referencefield3Field;
            }
            set
            {
                _referencefield3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Referencefield4
        {
            get
            {
                return _referencefield4Field;
            }
            set
            {
                _referencefield4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Referencefield5
        {
            get
            {
                return _referencefield5Field;
            }
            set
            {
                _referencefield5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DistributionJobNumber
        {
            get
            {
                return _distributionJobNumberField;
            }
            set
            {
                _distributionJobNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comments
        {
            get
            {
                return _commentsField;
            }
            set
            {
                _commentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ordernotes
        {
            get
            {
                return _ordernotesField;
            }
            set
            {
                _ordernotesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Shipcomplete
        {
            get
            {
                return _shipcompleteField;
            }
            set
            {
                _shipcompleteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderStatusCode
        {
            get
            {
                return _orderStatusCodeField;
            }
            set
            {
                _orderStatusCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProviderCode
        {
            get
            {
                return _providerCodeField;
            }
            set
            {
                _providerCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PriorityCode
        {
            get
            {
                return _priorityCodeField;
            }
            set
            {
                _priorityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WorkOrderTypeCode
        {
            get
            {
                return _workOrderTypeCodeField;
            }
            set
            {
                _workOrderTypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AffiliateCode
        {
            get
            {
                return _affiliateCodeField;
            }
            set
            {
                _affiliateCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MarketingSourceCode
        {
            get
            {
                return _marketingSourceCodeField;
            }
            set
            {
                _marketingSourceCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReleaseDate
        {
            get
            {
                return _releaseDateField;
            }
            set
            {
                _releaseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderSourceCode
        {
            get
            {
                return _orderSourceCodeField;
            }
            set
            {
                _orderSourceCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WorkOrderReference
        {
            get
            {
                return _workOrderReferenceField;
            }
            set
            {
                _workOrderReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CompleteByDate
        {
            get
            {
                return _completeByDateField;
            }
            set
            {
                _completeByDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PromotionCode
        {
            get
            {
                return _promotionCodeField;
            }
            set
            {
                _promotionCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalesTerritoryCode
        {
            get
            {
                return _salesTerritoryCodeField;
            }
            set
            {
                _salesTerritoryCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillingCode
        {
            get
            {
                return _billingCodeField;
            }
            set
            {
                _billingCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BudgetCenterCode
        {
            get
            {
                return _budgetCenterCodeField;
            }
            set
            {
                _budgetCenterCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExceptionType
        {
            get
            {
                return _exceptionTypeField;
            }
            set
            {
                _exceptionTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExceptionMessage
        {
            get
            {
                return _exceptionMessageField;
            }
            set
            {
                _exceptionMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("billToAddress", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyOrderImportOrderHeaderBillToAddress[] BillToAddress
        {
            get
            {
                return _billToAddressField;
            }
            set
            {
                _billToAddressField = value;
            }
        }

        


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("payments", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyOrderImportOrderHeaderPayments[] Payments
        {
            get
            {
                return _paymentsField;
            }
            set
            {
                _paymentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dynamicField")]
        public DynamicField[] DynamicField
        {
            get
            {
                return _dynamicFieldField;
            }
            set
            {
                _dynamicFieldField = value;
            }
        }

        /// <remarks/>
        [XmlElement("OrderDetail")]
        public MessageBodyOrderImportOrderHeaderOrderDetail[] OrderDetail
        {
            get
            {
                return _orderDetailField;
            }
            set
            {
                _orderDetailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyOrderImportOrderHeaderBillToAddress
    {

        private string _salutationField;

        private string _isResidentialField;

        private string _namefirstField;

        private string _namelastField;

        private string _nameMiddleField;

        private string _address1Field;

        private string _address2Field;

        private string _address3Field;

        private string _cityField;

        private string _stateProvinceField;

        private string _postalCodeField;

        private string _countryCodeField;

        private string _phoneWorkField;

        private string _phoneHomeField;

        private string _phoneCellField;

        private string _phonePagerField;

        private string _phoneOtherField;

        private string _faxField;

        private string _emailField;

        private string _usernameField;

        private string _typeCodeField;

        private string _memberIdField;

        private string _memberNumberField;

        private string _externMemberXRefField;

        private string _storePaymentInfoField;

        private string _taxNumberField;

        private string _originCodeField;

        private string _sourceCodeField;

        private string _promotionCodeField;

        private string _priceListCodeField;

        private MessageBodyOrderImportOrderHeaderBillToAddressOrganization[] _organizationField;

        private DynamicField[] _dynamicFieldField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Salutation
        {
            get
            {
                return _salutationField;
            }
            set
            {
                _salutationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsResidential
        {
            get
            {
                return _isResidentialField;
            }
            set
            {
                _isResidentialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Namefirst
        {
            get
            {
                return _namefirstField;
            }
            set
            {
                _namefirstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Namelast
        {
            get
            {
                return _namelastField;
            }
            set
            {
                _namelastField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NameMiddle
        {
            get
            {
                return _nameMiddleField;
            }
            set
            {
                _nameMiddleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Address1
        {
            get
            {
                return _address1Field;
            }
            set
            {
                _address1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Address2
        {
            get
            {
                return _address2Field;
            }
            set
            {
                _address2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Address3
        {
            get
            {
                return _address3Field;
            }
            set
            {
                _address3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City
        {
            get
            {
                return _cityField;
            }
            set
            {
                _cityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StateProvince
        {
            get
            {
                return _stateProvinceField;
            }
            set
            {
                _stateProvinceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostalCode
        {
            get
            {
                return _postalCodeField;
            }
            set
            {
                _postalCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CountryCode
        {
            get
            {
                return _countryCodeField;
            }
            set
            {
                _countryCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhoneWork
        {
            get
            {
                return _phoneWorkField;
            }
            set
            {
                _phoneWorkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhoneHome
        {
            get
            {
                return _phoneHomeField;
            }
            set
            {
                _phoneHomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhoneCell
        {
            get
            {
                return _phoneCellField;
            }
            set
            {
                _phoneCellField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhonePager
        {
            get
            {
                return _phonePagerField;
            }
            set
            {
                _phonePagerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhoneOther
        {
            get
            {
                return _phoneOtherField;
            }
            set
            {
                _phoneOtherField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fax
        {
            get
            {
                return _faxField;
            }
            set
            {
                _faxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email
        {
            get
            {
                return _emailField;
            }
            set
            {
                _emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Username
        {
            get
            {
                return _usernameField;
            }
            set
            {
                _usernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TypeCode
        {
            get
            {
                return _typeCodeField;
            }
            set
            {
                _typeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MemberId
        {
            get
            {
                return _memberIdField;
            }
            set
            {
                _memberIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MemberNumber
        {
            get
            {
                return _memberNumberField;
            }
            set
            {
                _memberNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExternMemberXRef
        {
            get
            {
                return _externMemberXRefField;
            }
            set
            {
                _externMemberXRefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StorePaymentInfo
        {
            get
            {
                return _storePaymentInfoField;
            }
            set
            {
                _storePaymentInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TaxNumber
        {
            get
            {
                return _taxNumberField;
            }
            set
            {
                _taxNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OriginCode
        {
            get
            {
                return _originCodeField;
            }
            set
            {
                _originCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SourceCode
        {
            get
            {
                return _sourceCodeField;
            }
            set
            {
                _sourceCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PromotionCode
        {
            get
            {
                return _promotionCodeField;
            }
            set
            {
                _promotionCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PriceListCode
        {
            get
            {
                return _priceListCodeField;
            }
            set
            {
                _priceListCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyOrderImportOrderHeaderBillToAddressOrganization[] Organization
        {
            get
            {
                return _organizationField;
            }
            set
            {
                _organizationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dynamicField")]
        public DynamicField[] DynamicField
        {
            get
            {
                return _dynamicFieldField;
            }
            set
            {
                _dynamicFieldField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyOrderImportOrderHeaderBillToAddressOrganization
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyOrderImportOrderHeaderPayments
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("paymentinfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyOrderImportOrderHeaderPaymentInfo[] MessageBodyOrderImportOrderHeaderPaymentInfo { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyOrderImportOrderHeaderPaymentInfo
    {

        private string _waivechargesField;

        private string _gatewaytransactionindexField;

        private string _paymenttokenField;

        private string _creditCardNumberField;

        private string _creditCardCidField;

        private string _expiryMonthField;

        private string _expiryYearField;

        private string _bankNameField;

        private string _bankAccountNameField;

        private string _bankAbaNumberField;

        private string _bankAccountNumberField;

        private string _checkNumberField;

        private string _bankAccountTypeField;

        private string _memberUsernameField;

        private string _budgetcentercodeField;

        private string _taxnumberField;

        private string _authorizercodeField;

        private string _authtrnnoField;

        private string _purchaseordernumberField;

        private string _purchaseorderdateField;

        private string _purchaseorderexpField;

        private string _thirdpartyaccountnumberField;

        private string _paymenttypenameField;

        private string _paymentstatuscodeField;

        private string _transactiontypecodeField;

        private string _primaryfororderField;

        private string _currencycodeField;

        private string _amountField;

        private string _settleamountField;

        private string _settlecurrencycodeField;

        private string _responsecodeField;

        private string _responsesubcodeField;

        private string _responsereasoncodeField;

        private string _responsereasontextField;

        private string _approvalcodeField;

        private string _addressvalidationcodeField;

        private string _cardcoderesponsecodeField;

        private string _notesField;

        private string _pendingreasonField;

        private string _transactionfeeField;

        private string _exchangerateField;

        private string _payerstatusField;

        private string _verifysignField;

        private string _paymentdateField;

        private string _pplsubscriberidField;

        private string _cardcodeField;

        private string _pmttermField;

        private string _pmtmethodField;

        private string _thirdpartybillnoField;

        private string _creditCardNameField;

        private string _creditCardSuffixField;

        private string _routingNumberField;

        private string _creditCardTypeField;
        private string _cvv;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Waivecharges
        {
            get
            {
                return _waivechargesField;
            }
            set
            {
                _waivechargesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Gatewaytransactionindex
        {
            get
            {
                return _gatewaytransactionindexField;
            }
            set
            {
                _gatewaytransactionindexField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Paymenttoken
        {
            get
            {
                return _paymenttokenField;
            }
            set
            {
                _paymenttokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreditCardNumber
        {
            get
            {
                return _creditCardNumberField;
            }
            set
            {
                _creditCardNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cvv
        {
            get { return _cvv; }
            set { _cvv = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreditCardCid
        {
            get
            {
                return _creditCardCidField;
            }
            set
            {
                _creditCardCidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExpiryMonth
        {
            get
            {
                return _expiryMonthField;
            }
            set
            {
                _expiryMonthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExpiryYear
        {
            get
            {
                return _expiryYearField;
            }
            set
            {
                _expiryYearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BankName
        {
            get
            {
                return _bankNameField;
            }
            set
            {
                _bankNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BankAccountName
        {
            get
            {
                return _bankAccountNameField;
            }
            set
            {
                _bankAccountNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BankAbaNumber
        {
            get
            {
                return _bankAbaNumberField;
            }
            set
            {
                _bankAbaNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BankAccountNumber
        {
            get
            {
                return _bankAccountNumberField;
            }
            set
            {
                _bankAccountNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CheckNumber
        {
            get
            {
                return _checkNumberField;
            }
            set
            {
                _checkNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BankAccountType
        {
            get
            {
                return _bankAccountTypeField;
            }
            set
            {
                _bankAccountTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MemberUsername
        {
            get
            {
                return _memberUsernameField;
            }
            set
            {
                _memberUsernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Budgetcentercode
        {
            get
            {
                return _budgetcentercodeField;
            }
            set
            {
                _budgetcentercodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Taxnumber
        {
            get
            {
                return _taxnumberField;
            }
            set
            {
                _taxnumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Authorizercode
        {
            get
            {
                return _authorizercodeField;
            }
            set
            {
                _authorizercodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Authtrnno
        {
            get
            {
                return _authtrnnoField;
            }
            set
            {
                _authtrnnoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Purchaseordernumber
        {
            get
            {
                return _purchaseordernumberField;
            }
            set
            {
                _purchaseordernumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Purchaseorderdate
        {
            get
            {
                return _purchaseorderdateField;
            }
            set
            {
                _purchaseorderdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Purchaseorderexp
        {
            get
            {
                return _purchaseorderexpField;
            }
            set
            {
                _purchaseorderexpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Thirdpartyaccountnumber
        {
            get
            {
                return _thirdpartyaccountnumberField;
            }
            set
            {
                _thirdpartyaccountnumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Paymenttypename
        {
            get
            {
                return _paymenttypenameField;
            }
            set
            {
                _paymenttypenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Paymentstatuscode
        {
            get
            {
                return _paymentstatuscodeField;
            }
            set
            {
                _paymentstatuscodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Transactiontypecode
        {
            get
            {
                return _transactiontypecodeField;
            }
            set
            {
                _transactiontypecodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Primaryfororder
        {
            get
            {
                return _primaryfororderField;
            }
            set
            {
                _primaryfororderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Currencycode
        {
            get
            {
                return _currencycodeField;
            }
            set
            {
                _currencycodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Amount
        {
            get
            {
                return _amountField;
            }
            set
            {
                _amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Settleamount
        {
            get
            {
                return _settleamountField;
            }
            set
            {
                _settleamountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Settlecurrencycode
        {
            get
            {
                return _settlecurrencycodeField;
            }
            set
            {
                _settlecurrencycodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Responsecode
        {
            get
            {
                return _responsecodeField;
            }
            set
            {
                _responsecodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Responsesubcode
        {
            get
            {
                return _responsesubcodeField;
            }
            set
            {
                _responsesubcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Responsereasoncode
        {
            get
            {
                return _responsereasoncodeField;
            }
            set
            {
                _responsereasoncodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Responsereasontext
        {
            get
            {
                return _responsereasontextField;
            }
            set
            {
                _responsereasontextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Approvalcode
        {
            get
            {
                return _approvalcodeField;
            }
            set
            {
                _approvalcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Addressvalidationcode
        {
            get
            {
                return _addressvalidationcodeField;
            }
            set
            {
                _addressvalidationcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cardcoderesponsecode
        {
            get
            {
                return _cardcoderesponsecodeField;
            }
            set
            {
                _cardcoderesponsecodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Notes
        {
            get
            {
                return _notesField;
            }
            set
            {
                _notesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pendingreason
        {
            get
            {
                return _pendingreasonField;
            }
            set
            {
                _pendingreasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Transactionfee
        {
            get
            {
                return _transactionfeeField;
            }
            set
            {
                _transactionfeeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Exchangerate
        {
            get
            {
                return _exchangerateField;
            }
            set
            {
                _exchangerateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Payerstatus
        {
            get
            {
                return _payerstatusField;
            }
            set
            {
                _payerstatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Verifysign
        {
            get
            {
                return _verifysignField;
            }
            set
            {
                _verifysignField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Paymentdate
        {
            get
            {
                return _paymentdateField;
            }
            set
            {
                _paymentdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pplsubscriberid
        {
            get
            {
                return _pplsubscriberidField;
            }
            set
            {
                _pplsubscriberidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cardcode
        {
            get
            {
                return _cardcodeField;
            }
            set
            {
                _cardcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pmtterm
        {
            get
            {
                return _pmttermField;
            }
            set
            {
                _pmttermField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pmtmethod
        {
            get
            {
                return _pmtmethodField;
            }
            set
            {
                _pmtmethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Thirdpartybillno
        {
            get
            {
                return _thirdpartybillnoField;
            }
            set
            {
                _thirdpartybillnoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreditCardName
        {
            get
            {
                return _creditCardNameField;
            }
            set
            {
                _creditCardNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreditCardSuffix
        {
            get
            {
                return _creditCardSuffixField;
            }
            set
            {
                _creditCardSuffixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RoutingNumber
        {
            get
            {
                return _routingNumberField;
            }
            set
            {
                _routingNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreditCardType
        {
            get
            {
                return _creditCardTypeField;
            }
            set
            {
                _creditCardTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyOrderImportOrderHeaderOrderDetail
    {
        private MessageBodyOrderImportOrderHeaderOrderDetailOrderLine _orderLine;

        public MessageBodyOrderImportOrderHeaderOrderDetailOrderLine OrderLine
        {
            get { return _orderLine; }
            set { _orderLine = value; }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyOrderImportOrderHeaderOrderDetailOrderLine
    {

        private MessageBodyOrderImportOrderHeaderOrderDetailOrderLineShippingInfo[] _shippingInfoField;

        private MessageBodyOrderImportOrderHeaderOrderDetailOrderLineCatalog[] _catalogField;

        private MessageBodyOrderImportOrderHeaderOrderDetailOrderLineShipToAddress[] _shipToAddressField;

        private DynamicField[] _dynamicFieldField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shippingInfo", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyOrderImportOrderHeaderOrderDetailOrderLineShippingInfo[] ShippingInfo
        {
            get
            {
                return _shippingInfoField;
            }
            set
            {
                _shippingInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("catalog", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyOrderImportOrderHeaderOrderDetailOrderLineCatalog[] Catalog
        {
            get
            {
                return _catalogField;
            }
            set
            {
                _catalogField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shipToAddress", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MessageBodyOrderImportOrderHeaderOrderDetailOrderLineShipToAddress[] ShipToAddress
        {
            get
            {
                return _shipToAddressField;
            }
            set
            {
                _shipToAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dynamicField")]
        public DynamicField[] DynamicField
        {
            get
            {
                return _dynamicFieldField;
            }
            set
            {
                _dynamicFieldField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyOrderImportOrderHeaderOrderDetailOrderLineShippingInfo
    {

        private string _shippingHandlingField;

        private string _discountField;

        private string _shipMethodCodeField;

        private string _delayShipUntilField;

        private string _shipNotesField;

        private string _isResidentialField;

        private string _providerCodeField;

        private string _shipperAttentionNeededField;

        private string _dateNeededField;

        private string _lastDropDateField;

        private string _declaredValueField;

        private string _insuranceChargeField;

        private string _shippingHandlingTaxField;

        private string _giftMessageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShippingHandling
        {
            get
            {
                return _shippingHandlingField;
            }
            set
            {
                _shippingHandlingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Discount
        {
            get
            {
                return _discountField;
            }
            set
            {
                _discountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipMethodCode
        {
            get
            {
                return _shipMethodCodeField;
            }
            set
            {
                _shipMethodCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DelayShipUntil
        {
            get
            {
                return _delayShipUntilField;
            }
            set
            {
                _delayShipUntilField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipNotes
        {
            get
            {
                return _shipNotesField;
            }
            set
            {
                _shipNotesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsResidential
        {
            get
            {
                return _isResidentialField;
            }
            set
            {
                _isResidentialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProviderCode
        {
            get
            {
                return _providerCodeField;
            }
            set
            {
                _providerCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipperAttentionNeeded
        {
            get
            {
                return _shipperAttentionNeededField;
            }
            set
            {
                _shipperAttentionNeededField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DateNeeded
        {
            get
            {
                return _dateNeededField;
            }
            set
            {
                _dateNeededField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastDropDate
        {
            get
            {
                return _lastDropDateField;
            }
            set
            {
                _lastDropDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeclaredValue
        {
            get
            {
                return _declaredValueField;
            }
            set
            {
                _declaredValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InsuranceCharge
        {
            get
            {
                return _insuranceChargeField;
            }
            set
            {
                _insuranceChargeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShippingHandlingTax
        {
            get
            {
                return _shippingHandlingTaxField;
            }
            set
            {
                _shippingHandlingTaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GiftMessage
        {
            get
            {
                return _giftMessageField;
            }
            set
            {
                _giftMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyOrderImportOrderHeaderOrderDetailOrderLineCatalog
    {

        private string _catalogitemField;

        private string _giftField;

        private string _releaseDateField;

        private string _updateTaxField;

        private string _updateShippingField;

        private string _checkAtpField;

        private string _skuField;

        private int _quantityField;

        private string _unitPriceField;

        private string _unitTaxField;

        private string _lineTaxField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Catalogitem
        {
            get
            {
                return _catalogitemField;
            }
            set
            {
                _catalogitemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Gift
        {
            get
            {
                return _giftField;
            }
            set
            {
                _giftField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReleaseDate
        {
            get
            {
                return _releaseDateField;
            }
            set
            {
                _releaseDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UpdateTax
        {
            get
            {
                return _updateTaxField;
            }
            set
            {
                _updateTaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UpdateShipping
        {
            get
            {
                return _updateShippingField;
            }
            set
            {
                _updateShippingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CheckAtp
        {
            get
            {
                return _checkAtpField;
            }
            set
            {
                _checkAtpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sku
        {
            get
            {
                return _skuField;
            }
            set
            {
                _skuField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Quantity
        {
            get
            {
                return _quantityField;
            }
            set
            {
                _quantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnitPrice
        {
            get
            {
                return _unitPriceField;
            }
            set
            {
                _unitPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnitTax
        {
            get
            {
                return _unitTaxField;
            }
            set
            {
                _unitTaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineTax
        {
            get
            {
                return _lineTaxField;
            }
            set
            {
                _lineTaxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public class MessageBodyOrderImportOrderHeaderOrderDetailOrderLineShipToAddress
    {

        private string _salutationField;

        private string _organizationField;

        private string _namefirstField;

        private string _namelastField;

        private string _nameMiddleField;

        private string _address1Field;

        private string _address2Field;

        private string _address3Field;

        private string _cityField;

        private string _stateProvinceField;

        private string _postalCodeField;

        private string _countryCodeField;

        private string _phoneWorkField;

        private string _phoneHomeField;

        private string _phoneCellField;

        private string _phonePagerField;

        private string _phoneOtherField;

        private string _faxField;

        private string _emailField;
        private string _isResidential;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Salutation
        {
            get
            {
                return _salutationField;
            }
            set
            {
                _salutationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Organization
        {
            get
            {
                return _organizationField;
            }
            set
            {
                _organizationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Namefirst
        {
            get
            {
                return _namefirstField;
            }
            set
            {
                _namefirstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Namelast
        {
            get
            {
                return _namelastField;
            }
            set
            {
                _namelastField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NameMiddle
        {
            get
            {
                return _nameMiddleField;
            }
            set
            {
                _nameMiddleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Address1
        {
            get
            {
                return _address1Field;
            }
            set
            {
                _address1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Address2
        {
            get
            {
                return _address2Field;
            }
            set
            {
                _address2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Address3
        {
            get
            {
                return _address3Field;
            }
            set
            {
                _address3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City
        {
            get
            {
                return _cityField;
            }
            set
            {
                _cityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StateProvince
        {
            get
            {
                return _stateProvinceField;
            }
            set
            {
                _stateProvinceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostalCode
        {
            get
            {
                return _postalCodeField;
            }
            set
            {
                _postalCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CountryCode
        {
            get
            {
                return _countryCodeField;
            }
            set
            {
                _countryCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhoneWork
        {
            get
            {
                return _phoneWorkField;
            }
            set
            {
                _phoneWorkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhoneHome
        {
            get
            {
                return _phoneHomeField;
            }
            set
            {
                _phoneHomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhoneCell
        {
            get
            {
                return _phoneCellField;
            }
            set
            {
                _phoneCellField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IsResidential
        {
            get { return _isResidential; }
            set { _isResidential = value; }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhonePager
        {
            get
            {
                return _phonePagerField;
            }
            set
            {
                _phonePagerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PhoneOther
        {
            get
            {
                return _phoneOtherField;
            }
            set
            {
                _phoneOtherField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fax
        {
            get
            {
                return _faxField;
            }
            set
            {
                _faxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email
        {
            get
            {
                return _emailField;
            }
            set
            {
                _emailField = value;
            }
        }
    }

    

    


}
