//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mozu.AubuchonDataAdapter.Domain.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ahotws.jaggedpeak.com/opentools/catalogimport.cfc")]
        public string Mozu_AubuchonDataAdapter_Domain_CatalogImportService_catalogimport_wrapService {
            get {
                return ((string)(this["Mozu_AubuchonDataAdapter_Domain_CatalogImportService_catalogimport_wrapService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ahotws.jaggedpeak.com/opentools/memberimport.cfc")]
        public string Mozu_AubuchonDataAdapter_Domain_Jp_CustomerImportService_memberimport_wrapService {
            get {
                return ((string)(this["Mozu_AubuchonDataAdapter_Domain_Jp_CustomerImportService_memberimport_wrapService" +
                    ""]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ahotws.jaggedpeak.com/opentools/fileupload.cfc")]
        public string Mozu_AubuchonDataAdapter_Domain_FileUploadService_fileupload_wrapService {
            get {
                return ((string)(this["Mozu_AubuchonDataAdapter_Domain_FileUploadService_fileupload_wrapService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ahotws.jaggedpeak.com/opentools/inventoryimport.cfc")]
        public string Mozu_AubuchonDataAdapter_Domain_InventoryImportService_inventoryimport_wrapService {
            get {
                return ((string)(this["Mozu_AubuchonDataAdapter_Domain_InventoryImportService_inventoryimport_wrapServic" +
                    "e"]));
            }
        }
    }
}
